name = "dnd-card-game-api"
main = "worker/index.ts"
compatibility_date = "2026-06-04"
workers_dev = true

[observability]
enabled = true

[vars]
CARD_CARDS_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTjZ6vCBGnVnho6axFA6mJTF2NpWL03IOSLF9Rhwittqq7HTgm3H4uieQZpwD6gSd9nhjjN3kG7TFPe/pub?gid=1807538627&single=true&output=csv"
CARD_STARTER_DECK_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTjZ6vCBGnVnho6axFA6mJTF2NpWL03IOSLF9Rhwittqq7HTgm3H4uieQZpwD6gSd9nhjjN3kG7TFPe/pub?gid=706545121&single=true&output=csv"
CARD_TRANSFORM_RULES_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTjZ6vCBGnVnho6axFA6mJTF2NpWL03IOSLF9Rhwittqq7HTgm3H4uieQZpwD6gSd9nhjjN3kG7TFPe/pub?gid=2061142189&single=true&output=csv"

[[durable_objects.bindings]]
name = "GAME_ROOMS"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[kv_namespaces]]
binding = "CARD_CATALOG_KV"
id = "26387ec714d7432890fe1fc717ac6705"
