export const COMMAND_TYPES = {
  JOIN_ROOM: "JOIN_ROOM",
  SET_CHARACTER: "SET_CHARACTER",
  PLAYER_READY: "PLAYER_READY",
  CANCEL_READY: "CANCEL_READY",
  DRAW_CARD: "DRAW_CARD",
  PLAY_CARD: "PLAY_CARD",
  DISCARD_CARD: "DISCARD_CARD",
  END_TURN: "END_TURN"
} as const;

export const EVENT_TYPES = {
  JOIN_ACCEPTED: "JOIN_ACCEPTED",
  PLAYER_JOINED: "PLAYER_JOINED",
  PLAYER_READY_CHANGED: "PLAYER_READY_CHANGED",
  PLAYER_CHARACTER_UPDATED: "PLAYER_CHARACTER_UPDATED",
  GAME_STARTED: "GAME_STARTED",
  CARD_DRAWN: "CARD_DRAWN",
  DECK_RECYCLED: "DECK_RECYCLED",
  CARD_PLAYED: "CARD_PLAYED",
  CARD_DISCARDED: "CARD_DISCARDED",
  CARD_ACTION_TRIGGERED: "CARD_ACTION_TRIGGERED",
  DISCARD_PHASE_STARTED: "DISCARD_PHASE_STARTED",
  CARD_TRANSFORMED: "CARD_TRANSFORMED",
  DAMAGE_APPLIED: "DAMAGE_APPLIED",
  HEAL_APPLIED: "HEAL_APPLIED",
  TURN_STARTED: "TURN_STARTED",
  TURN_ENDED: "TURN_ENDED",
  GAME_ENDED: "GAME_ENDED",
  GAME_STATE_SYNC: "GAME_STATE_SYNC",
  COMMAND_REJECTED: "COMMAND_REJECTED"
} as const;
